# you must create 'config.toml' accordingly this example

[Database]
NAME = 'template_bot'
#HOST = 'localhost'
#PORT = 27017
#USERNAME = 'root'
#PASSWORD = ''
#AUTH_SOURCE = 'admin'

[Bot]
TOKEN = ''
#SKIP_UPDATES = true

[Users]
ADMINS_IDS = [724477101]

[Log]
#FILE = '.log'
#LEVEL = 30
